#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api'

controllers:
    resource: ../../src/Controller/
    type: annotation
